steps:
- id: 'create_disk_for_nested_image'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - compute
    - disks
    - create
    - nested-agent-disk
    - --image-project
    - centos-cloud
    - --image-family
    - centos-7
    - --zone
    - ${_IMAGE_ZONE}
steps:
- name: ubuntu 
  id: 'nested_virtualization_spec'
  entrypoint: "bash"
  args:
    - '-c'
    - |
      cat <<END>packer-nested.json
      {
      "builders": [
        {
          "image_name": "nested-vm-image",
          "type": "googlecompute",
          "project_id": "$PROJECT_ID",
          "source_disk": "nested-agent-disk"
          "source_disk_zone": ${_IMAGE_ZONE}
          "licenses": ["https://www.googleapis.com/compute/v1/\
          projects/vm-options/global/licenses/enable-vmx"]
        }
       ]
      }
      END
- id: packer_nested_image
- name: 'gcr.io/$PROJECT_ID/packer'
  args:
  - build
  - -var
  - project_id=$PROJECT_ID
  - packer-nested.json

